### ISSUE TITLE
suggestion: add some screenshots

### ISSUE THREAD

**Issue by andreinitescu** [johankson/flipper#9]
Can I suggest adding some screenshots to the 'readme' file please? Ideally, for each control, have a screenshot for each platform.

**Comment by johankson** [comment]
Yes, I'll do that ASAP. However, the controls are very animation heavy and the screenshots will be limited in presenting what they actually do. Perhaps I'll try to link to some youtube footage as well.

**Comment by andreinitescu** [comment]
@johankson I suggest you use http://recordit.co/ to do screen recoding and produce GIFs, it's very cool.
 I learned about it from Twitter and from http://developer.telerik.com/featured/creating-micro-screencasts-hosted-free/

**Comment by johankson** [comment]
Alright! I'll check that out. Meanwhile I created some static screenshots. Warning though, I'm no designer! :)
